version: "3"
services:
  proxy:
    image: nginx:custom
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.htpasswd/:/etc/nginx/.htpasswd:ro
      - ./web:/var/www/viswaconsult.com/
      - ./certs/:/etc/nginx/ssl/
      - ./conf.d:/etc/nginx/conf.d
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
